/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 * CLIENTE SERVIDOR
 * Santiago Columba
 * Sexto Sistemas
 */
public class MenuTalleresColumba extends javax.swing.JFrame {

    /**
     * Creates new form MenuTalleresColumba
     */
    public MenuTalleresColumba() {
        initComponents();
        setTitle("Menú Talleres Columba");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repuesto = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contacto3 = new javax.swing.JButton();
        mecanico2 = new javax.swing.JButton();
        mecanico3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 520));
        setMinimumSize(new java.awt.Dimension(1000, 520));
        getContentPane().setLayout(null);

        repuesto.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        repuesto.setText("Repuestos");
        repuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repuestoActionPerformed(evt);
            }
        });
        getContentPane().add(repuesto);
        repuesto.setBounds(750, 280, 160, 31);

        salir.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(750, 360, 160, 31);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("MENÚ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(770, 140, 130, 45);

        contacto3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        contacto3.setText("Contactos");
        contacto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacto3ActionPerformed(evt);
            }
        });
        getContentPane().add(contacto3);
        contacto3.setBounds(750, 320, 160, 31);

        mecanico2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        mecanico2.setText("Cliente");
        mecanico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mecanico2ActionPerformed(evt);
            }
        });
        getContentPane().add(mecanico2);
        mecanico2.setBounds(750, 240, 160, 31);

        mecanico3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        mecanico3.setText("Mécanicos");
        mecanico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mecanico3ActionPerformed(evt);
            }
        });
        getContentPane().add(mecanico3);
        mecanico3.setBounds(750, 200, 160, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1040, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void repuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repuestoActionPerformed
    RepuestoTallerColumba ir = new RepuestoTallerColumba();
    ir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_repuestoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void contacto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacto3ActionPerformed
    ContactosTallerColumba ir = new ContactosTallerColumba();
    ir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_contacto3ActionPerformed

    private void mecanico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mecanico2ActionPerformed
    frmCliente ir = new frmCliente();
    ir.setVisible(true);
    this.setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_mecanico2ActionPerformed

    private void mecanico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mecanico3ActionPerformed
    MecanicoTallerColumba ir = new MecanicoTallerColumba();
    ir.setVisible(true);
    this.setVisible(false);  
    }//GEN-LAST:event_mecanico3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTalleresColumba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTalleresColumba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTalleresColumba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTalleresColumba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTalleresColumba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contacto3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mecanico2;
    private javax.swing.JButton mecanico3;
    private javax.swing.JButton repuesto;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
